### ISSUE TITLE
BUG: Error occurred during installation of the library.

### ISSUE THREAD

**Issue by ds6ga6** [stephenhky/pyqentangle#47]
Hi Stephen,

First off, I would like to commend you on the amazing work you have done on this project; it is clear that an incredible amount of time and effort has gone into its development.

But here is a error when i install it as follows

```
>pip install -U pyqentangle
Collecting pyqentangle
  Using cached pyqentangle-3.3.0.tar.gz (48 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      C:\Users\11648\AppData\Local\Temp\pip-build-env-u0m1ue04\overlay\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\11648\AppData\Local\Temp\pip-install-vx9z6ldi\pyqentangle_cff33e415f3a4f41947886a6b8ac28e8\pyqentangle\cythonmodule\interpolate_nocheck.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...


      def numerical_continuous_interpolation_nocheck_cython(np.ndarray xarray, np.ndarray yarray, double x):
          cdef int left = 0
          cdef int right = len(xarray) - 1
          cdef int idx = len(xarray) / 2
                                     ^
      ------------------------------------------------------------

      pyqentangle\cythonmodule\interpolate_nocheck.pyx:9:31: Cannot assign type 'double' to 'int'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          while (idx != 0 and idx != len(xarray) - 1) and (not (x >= xarray[idx] and x < xarray[idx + 1])):
              if x >= xarray[idx + 1]:
                  left = idx + 1
              elif x < xarray[idx]:
                  right = idx - 1
              idx = (left + right) / 2
                                   ^
      ------------------------------------------------------------

      pyqentangle\cythonmodule\interpolate_nocheck.pyx:15:29: Cannot assign type 'double' to 'int'
      Compiling pyqentangle/cythonmodule/interpolate_nocheck.pyx because it changed.
      [1/1] Cythonizing pyqentangle/cythonmodule/interpolate_nocheck.pyx
      Traceback (most recent call last):
        File "C:\Users\11648\anaconda3\envs\visgpt\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\11648\anaconda3\envs\visgpt\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main   
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\11648\anaconda3\envs\visgpt\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\11648\AppData\Local\Temp\pip-build-env-u0m1ue04\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\11648\AppData\Local\Temp\pip-build-env-u0m1ue04\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\11648\AppData\Local\Temp\pip-build-env-u0m1ue04\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\11648\AppData\Local\Temp\pip-build-env-u0m1ue04\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "C:\Users\11648\AppData\Local\Temp\pip-build-env-u0m1ue04\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\11648\AppData\Local\Temp\pip-build-env-u0m1ue04\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pyqentangle/cythonmodule/interpolate_nocheck.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I has try different python versions (including 3.8, 3.9, 3.11), both has the problem.

**Comment by stephenhky** [comment]
It used to work, but it seems that Cython has some updated that makes it no longer work. I am working on it. THanks for raising it to me!

**Comment by stephenhky** [comment]
Correction is proposed in this pull request: https://github.com/stephenhky/pyqentangle/pull/48
It is under the branch `division`.
I will merge it after I figured out there is nothing else that would cause a problem.

**Comment by stephenhky** [comment]
There is a new release that addresses the bugs: https://github.com/stephenhky/pyqentangle/releases/tag/3.3.1

You can install it with `pip` now.
